import fs from "node:fs/promises";
import path from "node:path";

const MARKDOWN_NOTICE =
  "> **Generated by Prompterium** — Do not edit this file manually. Edit `catalog/` in the Prompterium repository and run `prompterium sync`.\n\n";

const SHELL_NOTICE =
  "# Generated by Prompterium — do not edit manually. Edit `catalog/` in Prompterium and run `prompterium sync`.\n";

export const PROMPTERIUM_JSON_KEY = "_prompterium";

const JSON_NOTICE = "Do not edit manually. Edit catalog/ in Prompterium and run prompterium sync.";

const MARKDOWN_EXTENSIONS = new Set([".md", ".mdc"]);
const SHELL_EXTENSIONS = new Set([".sh", ".bash"]);

export function annotateSyncedContent(content: string, fileName: string): string {
  const ext = path.extname(fileName).toLowerCase();

  if (MARKDOWN_EXTENSIONS.has(ext)) {
    return annotateMarkdown(content);
  }
  if (SHELL_EXTENSIONS.has(ext)) {
    return annotateShell(content);
  }
  if (ext === ".json") {
    return annotateJson(content);
  }

  return content;
}

function annotateMarkdown(content: string): string {
  if (content.startsWith("---\n")) {
    const end = content.indexOf("\n---\n", 4);
    if (end !== -1) {
      const afterFrontmatter = end + 5;
      return content.slice(0, afterFrontmatter) + MARKDOWN_NOTICE + content.slice(afterFrontmatter);
    }
  }

  return MARKDOWN_NOTICE + content;
}

function annotateShell(content: string): string {
  const lines = content.split("\n");
  if (lines[0]?.startsWith("#!")) {
    lines.splice(1, 0, SHELL_NOTICE.trimEnd());
    return lines.join("\n");
  }

  return SHELL_NOTICE + content;
}

function annotateJson(content: string): string {
  const data = JSON.parse(content) as Record<string, unknown>;
  data[PROMPTERIUM_JSON_KEY] = {
    generated: true,
    notice: JSON_NOTICE,
  };
  return `${JSON.stringify(data, null, 2)}\n`;
}

export async function annotateSyncedTree(cursorDir: string): Promise<void> {
  const entries = await fs.readdir(cursorDir, { withFileTypes: true });
  for (const ent of entries) {
    const fullPath = path.join(cursorDir, ent.name);
    if (ent.isDirectory()) {
      await annotateSyncedTree(fullPath);
      continue;
    }
    if (!ent.isFile()) continue;

    const ext = path.extname(ent.name).toLowerCase();
    if (!MARKDOWN_EXTENSIONS.has(ext) && !SHELL_EXTENSIONS.has(ext) && ext !== ".json") {
      continue;
    }

    const content = await fs.readFile(fullPath, "utf8");
    const annotated = annotateSyncedContent(content, ent.name);
    if (annotated !== content) {
      await fs.writeFile(fullPath, annotated, "utf8");
    }
  }
}
